version: "3.9"

services:
  alloy:
    image: grafana/alloy:v1.10.1
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "12345:12345" # Alloy UI
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - --stability.level=experimental
      - /etc/alloy/config.alloy
    env_file:
      - .env